language: C

sudo: false

cache:
#  - apt
#  - pip
  directories:
    - $HOME/.cache/pip



before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log


git:
  depth: 3


matrix:
  include:
    # Linux builds
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - cmake-data
      before_install:
        - pip install --user cpp-coveralls
      script:
        #- cd build
        - df -h
        - cmake .
        - make -j2
      after_success:
        - coveralls -e test -e testdata -e cmake -e CMakeFiles -e ext

    # Windows x86 builds
    - os: linux
      compiler: i686-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - cmake
            - cmake-data
            - binutils-mingw-w64-i686
            - gcc-mingw-w64-i686
            - g++-mingw-w64-i686
      script:
        - df -h
        - cmake -DCMAKE_TOOLCHAIN_FILE=cmake/mingw-x86.cmake -DBOLIB2_EXECUTE_TEST=OFF .
        - make -j2

    # Windows x64 builds
    - os: linux
      compiler: x86_64-w64-mingw32-gcc
      addons:
        apt:
          packages:
            - cmake
            - cmake-data
            - binutils-mingw-w64-x86-64
            - gcc-mingw-w64-x86-64
            - g++-mingw-w64-x86-64
      script:
        - df -h
        - cmake -DCMAKE_TOOLCHAIN_FILE=cmake/mingw-x64.cmake -DBOLIB2_EXECUTE_TEST=OFF .
        - make -j2

    # Mac OSX builds
    - os: osx
      compiler: gcc
#     addons:
#       apt:
#         packages:
#           - cmake
#           - cmake-data
      script:
        - df -h
        - cmake .
        - make -j2

